
site_name: Eee's blog
site_url: https://eee616.github.io/Hello.github.lo/


nav:
  - 首页: index.md
  - 第一部分:
    - Part1/index.md
  - 第二部分:
    - Part2/index.md


theme:
  name: material
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换浅色模式
  
  font:
    text: Noto Sans SC
    code: JetBrains Mono
 
  icon:
    logo: material/book-open-page-variant
 
  features:
    - navigation.tabs         
    - navigation.tabs.sticky   
    - navigation.top           
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes

markdown_extensions:
  - attr_list
  - md_in_html
  
