
site_name: Eee's blog
site_url: https://eee616.github.io/Hello.github.lo/


nav:
  - 首页: index.md
  - 随笔:
    - Part1/index.md
  - 记事簿:
    - Part2/index.md


theme:
  name: material
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换浅色模式
  
  font:
    text: Noto Sans SC
    code: JetBrains Mono
 
  icon:
    logo: material/book-open-page-variant
 
  features:
    - navigation.tabs         
    - navigation.tabs.sticky   
    - navigation.top           
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes

markdown_extensions:
  - attr_list
  - md_in_html
  
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Eee616
    - icon: fontawesome/solid/paper-plane
      link: mailto:cy06-20@qq.com
  copyright: Copyright &copy; 2026 Eee

plugins:
  - search
  - blog:
      blog_dir: Part1
      archive: false
      categories: false
  - blog:
      blog_dir: Part2
      archive: false
      categories: false
